M48
; DRILL file {KiCad 7.0.10} date Saturday, March 16, 2024 at 11:25:46 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-16T23:25:46+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X48.65Y-32.85
X69.55Y-90.45
X78.2Y-34.15
X107.0Y-90.15
M30
